import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Arif Dev",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' data-arp=''>
			<body className={`antialiased`}>{children}</body>
		</html>
	);
}
