export const imageConfig = {
	photo1: "/images/photo1.jpg",
	photo2: "/images/photo2.jpg",
	photo3: "/images/photo3.jpg",
	photo4: "/images/photo4.jpg",
	photo5: "/images/photo5.jpg",
	photo6: "/images/photo6.jpg",
	photo7: "/images/photo7.jpg",
	photo8: "/images/photo8.jpg",
	photo9: "/images/photo9.jpg",
	photo10: "/images/photo10.jpg",
	photo11: "/images/photo11.jpg",
	photo12: "/images/photo12.jpg",
	photo13: "/images/photo13.jpg",
	photo14: "/images/photo14.jpg",
	photo15: "/images/photo15.jpg",
	photo16: "/images/photo16.jpg",
	photo17: "/images/photo17.jpg",
	photo18: "/images/photo18.jpg",
	photo19: "/images/photo19.jpg",
};
